### ISSUE TITLE
Driveasy - Full-Stack Capstone project - Kanban Board 

### ISSUE THREAD

**Issue by batoolfatima2135** [batoolfatima2135/Driveasy#10]
Hi,
We are two people in the group @batoolfatima2135  and @Othniel2471, 
Here is the link to our [project](https://github.com/users/batoolfatima2135/projects/11/views/1) 
here is the screenshot of the fresh kanban board
![Capture](https://github.com/batoolfatima2135/driveasy/assets/61277612/16523e92-8b3a-4880-aafa-22787e6bc09f)

**Comment by Meltrust** [comment]
Hi @batoolfatima2135,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have been assigned, have descriptions, and pointings according to spec ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
